### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by chenhuiphd** [Penn000/SpA-GAN_for_cloud_removal#2]
Does this code have a corresponding paper? thx

**Comment by Penn000** [comment]
The paper of this work is not yet released, maybe you can get some information by reading the `README`.

**Comment by 893205894** [comment]
hi，is  the paper  available now？ :-D

**Comment by med-omar** [comment]
hi，is the paper available now？

**Comment by Penn000** [comment]
hi, the draft is released at [https://arxiv.org/abs/2009.13015](https://arxiv.org/abs/2009.13015).
