### ISSUE TITLE
pre-model

### ISSUE THREAD

**Issue by chenhuiphd** [Penn000/SpA-GAN_for_cloud_removal#6]
Can you provide a pre-trained model? I use your model for testing, and found that some pictures output attention map is good, and some pictures output attention map is not good. I think it should be the reason for less iterations.
![0](https://user-images.githubusercontent.com/42506206/64057914-51f59680-cbd6-11e9-9100-9112e1106b4e.png)
![250](https://user-images.githubusercontent.com/42506206/64057915-59b53b00-cbd6-11e9-8c66-15b9ca6cae5a.png)

**Comment by Penn000** [comment]
@chenhuiphd hi, `pretrained_models/` is the model I have trained. SpA GAN is designed for thin cloud removal. Removing thick cloud from a single image is a condition limited problem, people often deal with it using multi-temporal image. This is why some results are not good on RICE2 dataset.
